version: "3"

services:

  zookeeper:
    image: bitnami/zookeeper:3.5.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.4.0
    ports:
      - 9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://127.0.0.1:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - 8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

  publisher:
    build:
      context: ./publisher
      dockerfile: ./Dockerfile
    environment:
      - KAFKA_BROKER_CONNECT=kafka://kafka:9092
    volumes:
      # 复制 wait-for-it 脚本
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      - kafka
      - zookeeper
    command: wait-for-it.sh kafka:9092 -- python test_pub_msg.py worker -l info --without-web
