version: "3"

services:

  zookeeper:
    image: bitnami/zookeeper:3.5.7
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:2.4.0
    ports:
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://127.0.0.1:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - 8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
    restart: unless-stopped

  publisher:
    build:
      context: ./publisher
      dockerfile: ./Dockerfile
    environment:
      - KAFKA_BROKER_CONNECT=kafka://kafka:9092
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      - kafka
      - zookeeper
    command: wait-for-it.sh kafka:9092 -- python test_pub_msg.py worker -l info --without-web
    restart: unless-stopped

  window:
    build:
      context: ../window
      dockerfile: ./Dockerfile
    environment:
      - KAFKA_BROKER_CONNECT=kafka://kafka:9092
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      - kafka
      - zookeeper
    command: wait-for-it.sh kafka:9092 -- python water_stream_window.py worker -l info --without-web
    restart: unless-stopped

  mongo:
    image: mongo:4.2.1
    ports:
    - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    ports:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
        - mongo
    restart: unless-stopped

  redis:
    image: redis:5
    ports:
      - 6379
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - 8081
    environment:
      - REDIS_HOSTS=local:redis:6379
    restart: unless-stopped

  flush:
    build:
      context: ../flush
      dockerfile: ./Dockerfile
    environment:
      - KAFKA_BROKER_CONNECT=kafka://kafka:9092
      - REDIS_HOST=redis://redis:6379
      - MONGO_HOST=mongodb://root:root@mongo:27017
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      - kafka
      - zookeeper
      - redis
      - mongo
    command: wait-for-it.sh kafka:9092 -- wait-for-it.sh redis:6379 -- wait-for-it.sh mongo:27017 -- python water_stream_flush.py worker -l info --without-web
    restart: unless-stopped
